name: Semantic Release

on:
  push:
    branches:
      - main    # Release sadece main'e push olunca çalışsın

permissions:
  contents: write   # tag ve commit push etmek için gerekli
  # issues: write   # release notlarını issue'lara yazdırmak istersen
  # pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # semantic-release için tag geçmişi lazım
          persist-credentials: false

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install python-semantic-release
        run: |
          python -m pip install --upgrade pip
          pip install python-semantic-release==9.12.0

      - name: Run semantic-release
        env:
          # python-semantic-release, GitHub için GH_TOKEN env var'ını bekliyor
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          semantic-release version --push --vcs-release